import type { DocumentaryEpisode } from "./documentaryEpisodes";
import type { DocumentarySourceId } from "../../shared/documentaryReels";

type Beat = [string, string, string, string, string, DocumentarySourceId[], boolean?];
const keys = ["label", "value", "line", "turn", "mechanism", "stakes", "meaning", "signOff"];
const scenes = (beats: Beat[]): DocumentaryEpisode["scenes"] =>
  beats.map((b, i) => ({
    key: keys[i]!,
    chapter: b[0],
    headline: b[1],
    detail: b[2],
    phrases: [b[3], b[4]],
    sources: b[5],
    ...(b[6] ? { analysis: true } : {}),
  }));

/** Different founders, different decisions. These replace the duplicate launch subjects. */
export const DOCUMENTARY_NEW_SUBJECTS: DocumentaryEpisode[] = [
  {
    id: "lowy-westfield",
    series: "The Deal",
    recipe: "grollo-documentary",
    releaseDate: "2026-09-16",
    period: "Westfield / 1959–2011 / historical AUD equivalents",
    treatment: "series-led-v1",
    scenes: scenes([
      [
        "FRANK LOWY",
        "Who pays for the next centre?",
        "Westfield / the early expansion",
        "Frank Lowy built Westfield with John Saunders.",
        "Their breakthrough was finding a way to fund the next shopping centre.",
        ["westfieldHistory"],
        true,
      ],
      [
        "1959 / BLACKTOWN",
        "The first centre.",
        "12 shops, two department stores, a supermarket",
        "In nineteen fifty-nine, they opened in Blacktown: twelve shops, two department stores and a supermarket.",
        "Then they took the company to the stock exchange.",
        ["westfieldHistory"],
      ],
      [
        "SEPTEMBER 1960 / THE FLOAT",
        "300,000 shares.",
        "Issue price: A$0.50 equivalent per share",
        "The nineteen sixty float issued three hundred thousand shares.",
        "At fifty Australian cents each in decimal equivalents, that represents one hundred and fifty thousand Australian dollars in issued shares.",
        ["westfieldHistory", "australianDecimalConversion"],
      ],
      [
        "1961 / HORNSBY",
        "A$690,000 equivalent.",
        "Reported centre cost / historical conversion",
        "Scentre's history says the float funded the Hornsby centre, which opened the following year.",
        "Its reported cost converts to six hundred and ninety thousand Australian dollars. These are historical equivalents, without inflation adjustment.",
        ["westfieldHistory", "australianDecimalConversion"],
      ],
      [
        "A DIFFERENT SCALE",
        "22 stores.",
        "Hornsby / 1961",
        "Hornsby had twenty-two stores.",
        "By the end of nineteen sixty-two, eight centres were completed or being developed in Sydney.",
        ["westfieldHistory"],
      ],
      [
        "BEYOND SYDNEY",
        "A business that could travel.",
        "Queensland, Victoria, then the United States",
        "Queensland followed in nineteen sixty-seven. Victoria in nineteen sixty-nine.",
        "In nineteen seventy-seven, Westfield bought its first American centre.",
        ["westfieldHistory"],
      ],
      [
        "2011 / STRATFORD",
        "Decades of expansion.",
        "London / a later chapter",
        "Decades later came London's Stratford City, in twenty eleven.",
        "The scale had changed completely. The early funding decision helps explain the journey.",
        ["westfieldHistory"],
        true,
      ],
      [
        "THE DECISION",
        "Build the next one.",
        "The Desk analysis / not an investment return",
        "This was more than a story about opening shops.",
        "Lowy and Saunders were building a company that could raise capital for the next centre.",
        ["westfieldHistory"],
        true,
      ],
    ]),
  },
  {
    id: "walker-rebuild",
    series: "The Deal",
    recipe: "grollo-documentary",
    releaseDate: "2026-09-23",
    period: "Lang Walker / 1964–2024 / AUD",
    treatment: "series-led-v1",
    scenes: scenes([
      [
        "LANG WALKER",
        "The developer who started again.",
        "Selling a portfolio was not retirement",
        "Lang Walker helped transform Sydney's waterfront.",
        "But twice, he sold major parts of his business, then kept developing.",
        ["walkerAward", "walkerObituary"],
      ],
      [
        "1964 / THE GROUNDWORK",
        "Father and son.",
        "Earthmoving and civil engineering",
        "He started with his father in nineteen sixty-four, in earthmoving and civil engineering.",
        "In nineteen seventy-two, he formed the Walker Group and expanded into property development.",
        ["walkerAward", "walkerHistory"],
      ],
      [
        "1994–1999 / THE FIRST EXIT",
        "Float. Then sell.",
        "Listed business / Australand transaction",
        "The company listed in nineteen ninety-four.",
        "Five years later, Walker sold his shares to Australand, reserving the right to use the Walker name again.",
        ["walkerHistory"],
      ],
      [
        "2003–2006 / ANOTHER CHAPTER",
        "The name returns.",
        "A new portfolio / a second major sale",
        "He brought that name back in two thousand and three.",
        "In two thousand and six, another portfolio sale to Mirvac was reported at more than one point one billion Australian dollars.",
        ["walkerHistory"],
      ],
      [
        "WHAT CHANGED HANDS",
        "> A$1.1bn.",
        "Reported portfolio transaction / 2006 / rounded",
        "That was a property and business transaction, not his personal profit.",
        "Walker kept industrial interests and some commercial and retail assets.",
        ["walkerHistory"],
        true,
      ],
      [
        "SELLING WAS NOT STOPPING",
        "Keep developing.",
        "Collins Square and Parramatta Square followed",
        "The exit preceded the global financial crisis. It was not the end of his career.",
        "Later projects included Melbourne's Collins Square and Sydney's Parramatta Square.",
        ["walkerAward"],
      ],
      [
        "2024 / THE LATER SCALE",
        "A$3.5bn.",
        "Parramatta Square / ABC's reported project figure",
        "In twenty twenty-four, the ABC described the completed Parramatta Square as a three point five billion Australian dollar project.",
        "Project scale, again, is different from a developer's profit.",
        ["walkerObituary"],
        true,
      ],
      [
        "THE BUSINESS PROGRESSION",
        "A sale. Another beginning.",
        "The Desk analysis / historical chapter",
        "Walker moved from shifting earth to reshaping city blocks.",
        "In between, he changed what he owned, sold major portfolios, and built again.",
        ["walkerHistory", "walkerAward"],
        true,
      ],
    ]),
  },
];
