/** Fixed product labels only. Never put reader input in an event or surface. */
export const ENGAGEMENT_EVENTS = [
  "social_open",
  "ask_query",
  "ask_share",
  "market_watch",
  "market_discover",
  "market_file_ask",
  "market_file_compare",
  "market_file_source",
  "market_file_share",
  "market_file_export",
  "market_compare",
  "market_compare_share",
  "comparison_watch",
  "comparison_refresh",
  "comparison_baseline_reset",
  "signal_watch",
  "signal_share",
  "story_share",
  "take_share",
  "brief_reshare",
  "story_open",
  "story_source",
  "story_ask",
  "newsletter_request",
  "ask_answer",
  "ask_unavailable",
  "ask_error",
] as const;
export const ENGAGEMENT_SURFACES = [
  "ask",
  "markets",
  "signals",
  "trends",
  "story",
  "brief",
  "today",
  "social",
  "queue",
  "subscribe",
] as const;
