/**
 * Drizzle schema for The Desk. JSON columns are typed against the Zod-derived
 * shapes in shared/schemas.ts so the database, server and client all agree on
 * what is in there.
 */
import {
  boolean,
  customType,
  double,
  index,
  int,
  json,
  mysqlEnum,
  mysqlTable,
  text,
  timestamp,
  varchar,
} from "drizzle-orm/mysql-core";

/**
 * MEDIUMBLOB column type — up to 16MB binary, plenty for compressed
 * hero images. Drizzle ships `binary` and `varbinary` but not blob,
 * so we declare it via customType and let mysql2 bind Buffers natively.
 */
const mediumBlob = customType<{ data: Buffer; driverData: Buffer }>({
  dataType: () => "mediumblob",
});
import type { EditionTopic, KeyMetrics, Signals } from "../../shared/schemas";

// ─── Users ──────────────────────────────────────────────────────────────────

export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  /** True when the user has an active paid subscription. The PaywallHint
   *  uses this to decide whether to render the soft paywall. */
  isPremium: boolean("isPremium").default(false).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

// ─── Editions ───────────────────────────────────────────────────────────────

export const editions = mysqlTable("editions", {
  id: int("id").autoincrement().primaryKey(),
  editionNumber: int("editionNumber").notNull().unique(),
  weekOf: varchar("weekOf", { length: 64 }).notNull(),
  weekRange: varchar("weekRange", { length: 128 }).notNull(),
  publishedAt: timestamp("publishedAt").defaultNow().notNull(),
  pdfUrl: text("pdfUrl"),
  readingTime: varchar("readingTime", { length: 32 }),
  /** Topic cards rendered in the Edition reader. */
  topics: json("topics").$type<EditionTopic[]>().notNull(),
  /** Short signal briefs. */
  signals: json("signals").$type<Signals>().notNull(),
  /** Full-text content of the source PDF for the search procedure. */
  fullText: text("fullText"),
  /** Week-over-week comparable metrics. */
  keyMetrics: json("keyMetrics").$type<KeyMetrics>(),
  /** AI-generated hero image URL. */
  heroImageUrl: text("heroImageUrl"),
  /** 2-4 sentence editorial opinion in Ruben's voice. */
  rubensTake: text("rubensTake"),
  /** Substack essay draft (saved through the admin panel). */
  substackDraftTitle: text("substackDraftTitle"),
  substackDraftSubtitle: text("substackDraftSubtitle"),
  substackDraftBody: text("substackDraftBody"),
  substackDraftImageUrl: text("substackDraftImageUrl"),
  /** Overall market stress signal — "low" / "moderate" / "high". Drives a
   *  single coloured dot on the edition hero, the way The Signal does. */
  marketStress: varchar("marketStress", { length: 16 }),
  /** Edition-level "dates to watch" forward calendar. JSON array of
   *  `{label, description}` entries (label is something like "May 21"
   *  or "Ongoing"). */
  datesToWatch: json("datesToWatch").$type<DateToWatch[] | null>(),
  /** SEO-optimised page title (~60 chars). Generated by the headline
   *  optimiser pass; falls back to the lead topic title. */
  metaTitle: varchar("metaTitle", { length: 160 }),
  /** SEO meta description (~155 chars) for the edition's page. */
  metaDescription: varchar("metaDescription", { length: 320 }),
  /** Social-share title (~70 chars) — punchier than metaTitle. */
  socialTitle: varchar("socialTitle", { length: 200 }),
  /** Social-share description (~200 chars). */
  socialDescription: varchar("socialDescription", { length: 400 }),
  /** Three alternative web headlines for the edition. The admin can
   *  promote one to the live edition or use them as A/B variants. */
  headlineVariants: json("headlineVariants").$type<string[] | null>(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type DateToWatch = {
  label: string;
  description: string;
};

export type Edition = typeof editions.$inferSelect;
export type InsertEdition = typeof editions.$inferInsert;

// ─── Daily feed items ───────────────────────────────────────────────────────

export const dailyFeedItems = mysqlTable("daily_feed_items", {
  id: int("id").autoincrement().primaryKey(),
  feedDate: varchar("feedDate", { length: 10 }).notNull(),
  title: varchar("title", { length: 512 }).notNull(),
  source: varchar("source", { length: 256 }).notNull(),
  sourceUrl: text("sourceUrl"),
  summary: text("summary").notNull(),
  category: varchar("category", { length: 64 }).notNull(),
  /** Per-item AI-generated hero image URL. Used by FeedLeadCard /
   *  StoryCard thumbnails — falls back to the category-tinted gradient
   *  plate if absent. */
  imageUrl: text("imageUrl"),
  /** 4-line "Persona: angle" string, generated by the LLM enrichment task. */
  partnerTag: text("partnerTag"),
  /** One-liner conversation starter. */
  sayThis: text("sayThis"),
  /** Editorial override — admin-authored note that appears on the story card
   *  as a highlighted Ruben quote. When set, takes visual precedence over
   *  the AI-generated sayThis. */
  rubensNote: text("rubensNote"),
  /** Story priority for the Today page lead/ordering. 0–100, higher
   *  outranks. Default 50, computed at ingest time by
   *  shared/feedPriority.ts. The admin can pin a story to 100 ("promote
   *  as lead") or drop one to 0 ("suppress") via feed.setPriority. */
  priority: int("priority").default(50).notNull(),
  promotedToEdition: boolean("promotedToEdition").default(false),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type DailyFeedItem = typeof dailyFeedItems.$inferSelect;
export type InsertDailyFeedItem = typeof dailyFeedItems.$inferInsert;

// ─── Subscribers ────────────────────────────────────────────────────────────

/**
 * Newsletter subscribers. Captured via the public Subscribe form; the
 * confirmation flow follows the classic double-opt-in pattern (a token
 * is emailed, the user clicks the link to confirm). Subscribers don't
 * need a user account — they're a separate, lighter-weight identity.
 *
 * `source` records WHERE the subscription came from (sidebar, hero,
 * subscribe modal, edition footer) so audience-growth can attribute
 * conversions to specific touchpoints.
 */
export const subscribers = mysqlTable("subscribers", {
  id: int("id").autoincrement().primaryKey(),
  email: varchar("email", { length: 320 }).notNull().unique(),
  name: varchar("name", { length: 128 }),
  /** Token used to confirm the email (double opt-in). Cleared on
   *  confirm. NULL once confirmed. */
  confirmToken: varchar("confirmToken", { length: 64 }),
  confirmedAt: timestamp("confirmedAt"),
  unsubscribedAt: timestamp("unsubscribedAt"),
  /** Free-form source attribution: "sidebar", "modal", "hero",
   *  "edition-footer", etc. */
  source: varchar("source", { length: 64 }),
  /** True when the subscriber has a paid tier on Substack. Synced
   *  manually or by webhook in production. */
  isPremium: boolean("isPremium").default(false).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type Subscriber = typeof subscribers.$inferSelect;
export type InsertSubscriber = typeof subscribers.$inferInsert;

// ─── Daily key metrics ──────────────────────────────────────────────────────

/**
 * Daily-refreshed market metrics shown in the Today page strip. One row
 * per metric (keyed by `metricKey`), upserted by the daily-metrics
 * GitHub Actions workflow. The `previousValue` is preserved across
 * updates so the UI can render a "vs. prior" delta without storing
 * history elsewhere.
 */
export const dailyMetrics = mysqlTable("daily_metrics", {
  id: int("id").autoincrement().primaryKey(),
  /** Stable key — "asx200", "audusd", "cash_rate". Used as the upsert key. */
  metricKey: varchar("metricKey", { length: 64 }).notNull().unique(),
  /** Human label — "ASX 200", "AUD / USD", "Cash rate". */
  label: varchar("label", { length: 128 }).notNull(),
  /** Current value as a display string, e.g. "8,210.43" or "0.6543" or "4.35%". */
  value: varchar("value", { length: 64 }).notNull(),
  /** Optional unit suffix, e.g. "%", "pts". UI may append. */
  unit: varchar("unit", { length: 16 }),
  /** Previous value before this update — used to compute deltas in the UI. */
  previousValue: varchar("previousValue", { length: 64 }),
  /** Source label — "Yahoo Finance", "RBA", "Manual". */
  source: varchar("source", { length: 64 }),
  /** Editorial context blurb under the value, e.g.
   *  "ANZ NOW EXPECTS EXTENDED HOLD" or "BELOW 60% FOR 7 STRAIGHT WEEKS". */
  context: varchar("context", { length: 256 }),
  /** Group key for organising tiles into sections on the metrics
   *  dashboard — "MACRO", "PROPERTY", "LABOUR", "MARKETS", "DEMOGRAPHICS". */
  groupKey: varchar("groupKey", { length: 32 }),
  /** Audit trail for news-extracted metrics — the URL the LLM pulled
   *  the figure from. Null for direct API sources (Yahoo / RBA / ABS)
   *  where the source is the canonical URL on the metric definition. */
  sourceUrl: text("sourceUrl"),
  /** As-of timestamp from the data source (not the upsert time). */
  asOf: timestamp("asOf").notNull(),
  /** Display order, lower = earlier. */
  displayOrder: int("displayOrder").default(100).notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().notNull(),
});

export type DailyMetric = typeof dailyMetrics.$inferSelect;
export type InsertDailyMetric = typeof dailyMetrics.$inferInsert;

/**
 * Append-only history of metric values. One row per upsert, so we can
 * draw a sparkline next to the current value on the dashboard. Cheap to
 * write (rate is one row per metric per day) and bounded — ~30 metrics ×
 * 365 days ≈ 11k rows per year.
 */
export const dailyMetricHistory = mysqlTable(
  "daily_metric_history",
  {
    id: int("id").autoincrement().primaryKey(),
    metricKey: varchar("metricKey", { length: 64 }).notNull(),
    numericValue: double("numericValue").notNull(),
    recordedAt: timestamp("recordedAt").defaultNow().notNull(),
  },
  (t) => ({
    keyRecorded: index("idx_metric_history_key_recorded").on(
      t.metricKey,
      t.recordedAt
    ),
  })
);

export type DailyMetricHistory = typeof dailyMetricHistory.$inferSelect;
export type InsertDailyMetricHistory = typeof dailyMetricHistory.$inferInsert;

// ─── Feedback submissions ──────────────────────────────────────────────────

/**
 * Reader-submitted feedback during the partner-testing window. Captured
 * via the floating Feedback button on every page. Each entry records the
 * reader's note, the page they were on, their user-agent, and an
 * optional contact email so the admin can follow up.
 *
 * `kind` partitions submissions into Bug / Idea / Praise so the inbox
 * is triageable at a glance. `status` flips from "new" to "reviewed"
 * once the admin reads it; nothing's auto-archived.
 */
export const feedbackSubmissions = mysqlTable("feedback_submissions", {
  id: int("id").autoincrement().primaryKey(),
  kind: varchar("kind", { length: 16 }).notNull(), // "bug" | "idea" | "praise"
  message: text("message").notNull(),
  pageUrl: varchar("pageUrl", { length: 512 }),
  userAgent: varchar("userAgent", { length: 512 }),
  contactEmail: varchar("contactEmail", { length: 320 }),
  /** Free-form reporter label — "Ruben's friend Sarah", "broker tester",
   *  etc. Captured so the admin doesn't have to remember who submitted
   *  what during a wide testing window. */
  reporterLabel: varchar("reporterLabel", { length: 128 }),
  status: varchar("status", { length: 16 }).default("new").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type FeedbackSubmission = typeof feedbackSubmissions.$inferSelect;
export type InsertFeedbackSubmission = typeof feedbackSubmissions.$inferInsert;

// ─── Edition asset blobs (hero + substack images) ──────────────────────────

/**
 * Binary storage for AI-generated edition images. Lives in its own table
 * so the large mediumblob never travels with editions.list / getById
 * unless explicitly selected. The `editions.heroImageUrl` and
 * `editions.substackDraftImageUrl` columns store a short
 * `/api/images/edition/:id/:kind` URL pointing at a row in here.
 *
 * One row per (editionId, kind). Re-generating overwrites the latest
 * row rather than appending — historical images aren't useful and
 * blob churn is cheap at this scale.
 */
export const editionAssets = mysqlTable("edition_assets", {
  id: int("id").autoincrement().primaryKey(),
  editionId: int("editionId").notNull(),
  /** "hero" or "substack". Free-form short string keeps future asset
   *  kinds (story thumbs, etc.) easy without another schema change. */
  kind: varchar("kind", { length: 32 }).notNull(),
  contentType: varchar("contentType", { length: 64 }).notNull(),
  /** WebP / PNG bytes. mediumblob = up to 16MB; we compress to <300KB. */
  bytes: mediumBlob("bytes").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type EditionAsset = typeof editionAssets.$inferSelect;
export type InsertEditionAsset = typeof editionAssets.$inferInsert;

// ─── Featured LinkedIn posts ────────────────────────────────────────────────

/**
 * Hand-curated LinkedIn posts that surface on the Today page as a "Ruben
 * on LinkedIn" strip. LinkedIn has no scrape-friendly API, so the admin
 * pastes the URL + excerpt manually. The site renders cards that link
 * back to the original post — readers finish the read on LinkedIn, which
 * doubles as engagement / follower acquisition for the brand.
 */
export const featuredLinkedInPosts = mysqlTable("featured_linkedin_posts", {
  id: int("id").autoincrement().primaryKey(),
  /** Canonical URL to the LinkedIn post (linkedin.com/posts/... or /feed/update/...). */
  postUrl: varchar("postUrl", { length: 1024 }).notNull(),
  /** 1-3 sentence pull from the post body. Plain text, no markup. */
  excerpt: text("excerpt").notNull(),
  /** Author display name; defaults to Ruben. Stored so we can feature
   *  guest posts down the line. */
  authorName: varchar("authorName", { length: 128 }).default("Ruben Laubscher").notNull(),
  /** Lower numbers sort first. Default 100 so new entries land at the end. */
  displayOrder: int("displayOrder").default(100).notNull(),
  /** Soft-hide flag — set false to remove from the page without deleting
   *  the row. */
  isLive: boolean("isLive").default(true).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type FeaturedLinkedInPost = typeof featuredLinkedInPosts.$inferSelect;
export type InsertFeaturedLinkedInPost = typeof featuredLinkedInPosts.$inferInsert;

// ─── Reading queue ──────────────────────────────────────────────────────────

export const readingQueue = mysqlTable("reading_queue", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  feedItemId: int("feedItemId"),
  customUrl: text("customUrl"),
  customTitle: varchar("customTitle", { length: 512 }),
  articleText: text("articleText"),
  isRead: boolean("isRead").default(false).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type ReadingQueueItem = typeof readingQueue.$inferSelect;
export type InsertReadingQueueItem = typeof readingQueue.$inferInsert;

// ─── Weekly notes ───────────────────────────────────────────────────────────

export const weeklyNotes = mysqlTable("weekly_notes", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  /** "2026-W17" style week identifier. */
  weekId: varchar("weekId", { length: 16 }).notNull(),
  content: text("content").notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type WeeklyNote = typeof weeklyNotes.$inferSelect;
export type InsertWeeklyNote = typeof weeklyNotes.$inferInsert;

// ─── Conversation tracker ───────────────────────────────────────────────────

export const conversationTracker = mysqlTable("conversation_tracker", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  editionId: int("editionId"),
  lineText: text("lineText").notNull(),
  usedWithCategory: varchar("usedWithCategory", { length: 128 }),
  usedAt: timestamp("usedAt").defaultNow().notNull(),
});

export type ConversationEntry = typeof conversationTracker.$inferSelect;
export type InsertConversationEntry = typeof conversationTracker.$inferInsert;
