/**
 * Drizzle schema for The Desk. JSON columns are typed against the Zod-derived
 * shapes in shared/schemas.ts so the database, server and client all agree on
 * what is in there.
 */
import {
  boolean,
  int,
  json,
  mysqlEnum,
  mysqlTable,
  text,
  timestamp,
  varchar,
} from "drizzle-orm/mysql-core";
import type { EditionTopic, KeyMetrics, Signals } from "../../shared/schemas";

// ─── Users ──────────────────────────────────────────────────────────────────

export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

// ─── Editions ───────────────────────────────────────────────────────────────

export const editions = mysqlTable("editions", {
  id: int("id").autoincrement().primaryKey(),
  editionNumber: int("editionNumber").notNull().unique(),
  weekOf: varchar("weekOf", { length: 64 }).notNull(),
  weekRange: varchar("weekRange", { length: 128 }).notNull(),
  publishedAt: timestamp("publishedAt").defaultNow().notNull(),
  pdfUrl: text("pdfUrl"),
  readingTime: varchar("readingTime", { length: 32 }),
  /** Topic cards rendered in the Edition reader. */
  topics: json("topics").$type<EditionTopic[]>().notNull(),
  /** Short signal briefs. */
  signals: json("signals").$type<Signals>().notNull(),
  /** Full-text content of the source PDF for the search procedure. */
  fullText: text("fullText"),
  /** Week-over-week comparable metrics. */
  keyMetrics: json("keyMetrics").$type<KeyMetrics>(),
  /** AI-generated hero image URL. */
  heroImageUrl: text("heroImageUrl"),
  /** 2-4 sentence editorial opinion in Ruben's voice. */
  rubensTake: text("rubensTake"),
  /** Substack essay draft (saved through the admin panel). */
  substackDraftTitle: text("substackDraftTitle"),
  substackDraftSubtitle: text("substackDraftSubtitle"),
  substackDraftBody: text("substackDraftBody"),
  substackDraftImageUrl: text("substackDraftImageUrl"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type Edition = typeof editions.$inferSelect;
export type InsertEdition = typeof editions.$inferInsert;

// ─── Daily feed items ───────────────────────────────────────────────────────

export const dailyFeedItems = mysqlTable("daily_feed_items", {
  id: int("id").autoincrement().primaryKey(),
  feedDate: varchar("feedDate", { length: 10 }).notNull(),
  title: varchar("title", { length: 512 }).notNull(),
  source: varchar("source", { length: 256 }).notNull(),
  sourceUrl: text("sourceUrl"),
  summary: text("summary").notNull(),
  category: varchar("category", { length: 64 }).notNull(),
  /** 4-line "Persona: angle" string, generated by the LLM enrichment task. */
  partnerTag: text("partnerTag"),
  /** One-liner conversation starter. */
  sayThis: text("sayThis"),
  promotedToEdition: boolean("promotedToEdition").default(false),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type DailyFeedItem = typeof dailyFeedItems.$inferSelect;
export type InsertDailyFeedItem = typeof dailyFeedItems.$inferInsert;

// ─── Reading queue ──────────────────────────────────────────────────────────

export const readingQueue = mysqlTable("reading_queue", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  feedItemId: int("feedItemId"),
  customUrl: text("customUrl"),
  customTitle: varchar("customTitle", { length: 512 }),
  articleText: text("articleText"),
  isRead: boolean("isRead").default(false).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type ReadingQueueItem = typeof readingQueue.$inferSelect;
export type InsertReadingQueueItem = typeof readingQueue.$inferInsert;

// ─── Weekly notes ───────────────────────────────────────────────────────────

export const weeklyNotes = mysqlTable("weekly_notes", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  /** "2026-W17" style week identifier. */
  weekId: varchar("weekId", { length: 16 }).notNull(),
  content: text("content").notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type WeeklyNote = typeof weeklyNotes.$inferSelect;
export type InsertWeeklyNote = typeof weeklyNotes.$inferInsert;

// ─── Conversation tracker ───────────────────────────────────────────────────

export const conversationTracker = mysqlTable("conversation_tracker", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  editionId: int("editionId"),
  lineText: text("lineText").notNull(),
  usedWithCategory: varchar("usedWithCategory", { length: 128 }),
  usedAt: timestamp("usedAt").defaultNow().notNull(),
});

export type ConversationEntry = typeof conversationTracker.$inferSelect;
export type InsertConversationEntry = typeof conversationTracker.$inferInsert;
