/**
 * Drizzle schema for The Desk. JSON columns are typed against the Zod-derived
 * shapes in shared/schemas.ts so the database, server and client all agree on
 * what is in there.
 */
import {
  boolean,
  int,
  json,
  mysqlEnum,
  mysqlTable,
  text,
  timestamp,
  varchar,
} from "drizzle-orm/mysql-core";
import type { EditionTopic, KeyMetrics, Signals } from "../../shared/schemas";

// ─── Users ──────────────────────────────────────────────────────────────────

export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  /** True when the user has an active paid subscription. The PaywallHint
   *  uses this to decide whether to render the soft paywall. */
  isPremium: boolean("isPremium").default(false).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

// ─── Editions ───────────────────────────────────────────────────────────────

export const editions = mysqlTable("editions", {
  id: int("id").autoincrement().primaryKey(),
  editionNumber: int("editionNumber").notNull().unique(),
  weekOf: varchar("weekOf", { length: 64 }).notNull(),
  weekRange: varchar("weekRange", { length: 128 }).notNull(),
  publishedAt: timestamp("publishedAt").defaultNow().notNull(),
  pdfUrl: text("pdfUrl"),
  readingTime: varchar("readingTime", { length: 32 }),
  /** Topic cards rendered in the Edition reader. */
  topics: json("topics").$type<EditionTopic[]>().notNull(),
  /** Short signal briefs. */
  signals: json("signals").$type<Signals>().notNull(),
  /** Full-text content of the source PDF for the search procedure. */
  fullText: text("fullText"),
  /** Week-over-week comparable metrics. */
  keyMetrics: json("keyMetrics").$type<KeyMetrics>(),
  /** AI-generated hero image URL. */
  heroImageUrl: text("heroImageUrl"),
  /** 2-4 sentence editorial opinion in Ruben's voice. */
  rubensTake: text("rubensTake"),
  /** Substack essay draft (saved through the admin panel). */
  substackDraftTitle: text("substackDraftTitle"),
  substackDraftSubtitle: text("substackDraftSubtitle"),
  substackDraftBody: text("substackDraftBody"),
  substackDraftImageUrl: text("substackDraftImageUrl"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type Edition = typeof editions.$inferSelect;
export type InsertEdition = typeof editions.$inferInsert;

// ─── Daily feed items ───────────────────────────────────────────────────────

export const dailyFeedItems = mysqlTable("daily_feed_items", {
  id: int("id").autoincrement().primaryKey(),
  feedDate: varchar("feedDate", { length: 10 }).notNull(),
  title: varchar("title", { length: 512 }).notNull(),
  source: varchar("source", { length: 256 }).notNull(),
  sourceUrl: text("sourceUrl"),
  summary: text("summary").notNull(),
  category: varchar("category", { length: 64 }).notNull(),
  /** Per-item AI-generated hero image URL. Used by FeedLeadCard /
   *  StoryCard thumbnails — falls back to the category-tinted gradient
   *  plate if absent. */
  imageUrl: text("imageUrl"),
  /** 4-line "Persona: angle" string, generated by the LLM enrichment task. */
  partnerTag: text("partnerTag"),
  /** One-liner conversation starter. */
  sayThis: text("sayThis"),
  promotedToEdition: boolean("promotedToEdition").default(false),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type DailyFeedItem = typeof dailyFeedItems.$inferSelect;
export type InsertDailyFeedItem = typeof dailyFeedItems.$inferInsert;

// ─── Subscribers ────────────────────────────────────────────────────────────

/**
 * Newsletter subscribers. Captured via the public Subscribe form; the
 * confirmation flow follows the classic double-opt-in pattern (a token
 * is emailed, the user clicks the link to confirm). Subscribers don't
 * need a user account — they're a separate, lighter-weight identity.
 *
 * `source` records WHERE the subscription came from (sidebar, hero,
 * subscribe modal, edition footer) so audience-growth can attribute
 * conversions to specific touchpoints.
 */
export const subscribers = mysqlTable("subscribers", {
  id: int("id").autoincrement().primaryKey(),
  email: varchar("email", { length: 320 }).notNull().unique(),
  name: varchar("name", { length: 128 }),
  /** Token used to confirm the email (double opt-in). Cleared on
   *  confirm. NULL once confirmed. */
  confirmToken: varchar("confirmToken", { length: 64 }),
  confirmedAt: timestamp("confirmedAt"),
  unsubscribedAt: timestamp("unsubscribedAt"),
  /** Free-form source attribution: "sidebar", "modal", "hero",
   *  "edition-footer", etc. */
  source: varchar("source", { length: 64 }),
  /** True when the subscriber has a paid tier on Substack. Synced
   *  manually or by webhook in production. */
  isPremium: boolean("isPremium").default(false).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type Subscriber = typeof subscribers.$inferSelect;
export type InsertSubscriber = typeof subscribers.$inferInsert;

// ─── Featured LinkedIn posts ────────────────────────────────────────────────

/**
 * Hand-curated LinkedIn posts that surface on the Today page as a "Ruben
 * on LinkedIn" strip. LinkedIn has no scrape-friendly API, so the admin
 * pastes the URL + excerpt manually. The site renders cards that link
 * back to the original post — readers finish the read on LinkedIn, which
 * doubles as engagement / follower acquisition for the brand.
 */
export const featuredLinkedInPosts = mysqlTable("featured_linkedin_posts", {
  id: int("id").autoincrement().primaryKey(),
  /** Canonical URL to the LinkedIn post (linkedin.com/posts/... or /feed/update/...). */
  postUrl: varchar("postUrl", { length: 1024 }).notNull(),
  /** 1-3 sentence pull from the post body. Plain text, no markup. */
  excerpt: text("excerpt").notNull(),
  /** Author display name; defaults to Ruben. Stored so we can feature
   *  guest posts down the line. */
  authorName: varchar("authorName", { length: 128 }).default("Ruben Laubscher").notNull(),
  /** Lower numbers sort first. Default 100 so new entries land at the end. */
  displayOrder: int("displayOrder").default(100).notNull(),
  /** Soft-hide flag — set false to remove from the page without deleting
   *  the row. */
  isLive: boolean("isLive").default(true).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type FeaturedLinkedInPost = typeof featuredLinkedInPosts.$inferSelect;
export type InsertFeaturedLinkedInPost = typeof featuredLinkedInPosts.$inferInsert;

// ─── Reading queue ──────────────────────────────────────────────────────────

export const readingQueue = mysqlTable("reading_queue", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  feedItemId: int("feedItemId"),
  customUrl: text("customUrl"),
  customTitle: varchar("customTitle", { length: 512 }),
  articleText: text("articleText"),
  isRead: boolean("isRead").default(false).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type ReadingQueueItem = typeof readingQueue.$inferSelect;
export type InsertReadingQueueItem = typeof readingQueue.$inferInsert;

// ─── Weekly notes ───────────────────────────────────────────────────────────

export const weeklyNotes = mysqlTable("weekly_notes", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  /** "2026-W17" style week identifier. */
  weekId: varchar("weekId", { length: 16 }).notNull(),
  content: text("content").notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type WeeklyNote = typeof weeklyNotes.$inferSelect;
export type InsertWeeklyNote = typeof weeklyNotes.$inferInsert;

// ─── Conversation tracker ───────────────────────────────────────────────────

export const conversationTracker = mysqlTable("conversation_tracker", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  editionId: int("editionId"),
  lineText: text("lineText").notNull(),
  usedWithCategory: varchar("usedWithCategory", { length: 128 }),
  usedAt: timestamp("usedAt").defaultNow().notNull(),
});

export type ConversationEntry = typeof conversationTracker.$inferSelect;
export type InsertConversationEntry = typeof conversationTracker.$inferInsert;
